### ISSUE TITLE
Скрипт iptables для маршрутизации по выгрузке

### ISSUE THREAD

**Issue by vibornoff** [AntiZapret/antizapret#44]
Предлагаю по аналогии с *iptables-block-gosnet.sh* и *iptables-ipset-block-gosnet.sh* сделать скрипты для заворачивания попавших в черный список ресурсов в отдельный маршрут.

Таким образом обладатели всяких там xyzWRT и домашних линуксов смогут настроить автоматический обход черных списков без необходимости гнать весь свой траффик через VPN.

**Comment by msva** [comment]
1) этот реквест не совсем для этого репозитория
2) patches are welcome ;)
