### ISSUE TITLE
вот реальный черный список

### ISSUE THREAD

**Issue by cybermerlin** [AntiZapret/antizapret#45]
ittown.info/black-list/black-list.ip

**Comment by r-vishnevsky-parc** [comment]
Совершенно не исключаю, но особенно реальным выглядит последний адрес: **255.255.255.255**

**Comment by cybermerlin** [comment]
по всей видимости атаки кто-то осуществлял с подменой адреса на найденный Вами

**Comment by msva** [comment]
Приведённый чёрный список не имеет ничего общего с темой данного репозитория, например.
