### ISSUE TITLE
Поменялся адрес 398-fz.rkn.gov.ru

### ISSUE THREAD

**Issue by ache** [AntiZapret/antizapret#47]
Новый адрес покрывается блоком 46.61.208.0/24
Возможно, старый блок надо убрать:
\# name: 398-fz.rkn.gov.ru
\# netname: BROADBAND_INTERNET_ACCESS
\# descr: BROADBAND INTERNET ACCESS FOR CUSTOMERS ROSTELECOM
\# origin: AS12389
\# (?) 188.254.0.0/17
188.254.0.0/20

**Comment by msva** [comment]
На самом деле, нет:
`398-fz.rkn.gov.ru has address 46.61.232.10`
Они, судя по всему, хостят его на сервере с IP из "домашнего" диапазона, не имея своей подсети :(

**Comment by ache** [comment]
Да, не покрывается, проглядел. Тем не менее, это новый адрес. Старый в списке в 188.254.0.0/20.

**Comment by ache** [comment]
Для нового надо 46.61.128.0/17

**Comment by msva** [comment]
В письме от Сб, 16 мая 2015 05:22:44 пользователь Ache написал:
> Для нового надо 46.61.128.0/17

Ну, я в коммите просто не тот issue упомянул :) Я, в общем, в последнем 
коммите вообще его убрал (т.к. при блокировке по "домашним" диапазонам, как 
показывает практика, больше страдают простые пользователи) 

-- 
Best regards,
mva

**Comment by ache** [comment]
А, вижу коммит. Вот этот блок надо ещё поменять:
```
# name: eais.rkn.gov.ru nap.rkn.gov.ru
# netname: MMT
# descr: MMT NPROD CMS 11-27194
# origin: AS12389
# (?) 46.61.128.0/17
46.61.208.0/24
```
На 46.61.128.0/17. Новый адрес 46.61.232.10 не влазит в 46.61.208.0/24

**Comment by msva** [comment]
Ну, тут вся печаль в том, что
```
inetnum:        46.61.210.0 - 46.61.241.255
netname:        BROADBAND_INTERNET_ACCESS
descr:          BROADBAND INTERNET ACCESS FOR CUSTOMERS ROSTELECOM
```

То ли они читают эту репу, то ли у них там всё делается школьниками на домашних серверах, но если вот так запросто заблочить весь /17, то все абоненты всего ростелекома попадут под раздачу :(

**Comment by ache** [comment]
Мда. Тогда просто внести один адрес 46.61.232.10/32

**Comment by ache** [comment]
Он теперьл для всех  398-fz.rkn.gov.ru 97-fz.rkn.gov.ru eais.rkn.gov.ru nap.rkn.gov.ru
А 46.61.208.0/24 убрать
