### ISSUE TITLE
Новая сетка Главного радиочастотного центра

### ISSUE THREAD

**Issue by ache** [AntiZapret/antizapret#54]
Вот тут поменять на 194.165.22.0/24 и добавить 194.165.23.0/24

\# name: Гос. радио-частотный Центр (ГРЧЦ)
\# netname: GRFC-NET
\# descr: Federal Unitary State Enterprise General Radio Freqency Centre
\# origin: AS196641
194.165.22.0/23

**Comment by msva** [comment]
Но ведь это и есть `194.165.22.0/23`, не?

**Comment by ache** [comment]
Пардон, да, он и есть, я ступил и просто скопировал хуиз(
