### ISSUE TITLE
Вот теперь новый IP 77.37.208.110

### ISSUE THREAD

**Issue by ache** [AntiZapret/antizapret#55]
На основании http://ruslanleviev.livejournal.com/34401.html там в деталях что с него идёт.
Выглядит как скромный сервер для whois, а на самом деле сканящий скрипт.

**Comment by msva** [comment]
```
role:           NCNET NCC Operations
address:        National Cable Networks
```
Это обычный "хомячковый" провайдер. И шанс, что этот IP потом, спустя месяц, например, или полгода, неважно, достанется ни в чём не повинному обычному юзеру - достаточно высокий.

**Comment by ache** [comment]
А разве не может то же самое произойти с любым IP из списка? Без тест скрипта по проверке прежней принадлежности подсеток или доменов нельзя быть уверенным. Единственный бесплатный сервис, который я нашёл, выдающий IP History, выдаёт слишком мало инфы по годам для вердикта http://viewdns.info/iphistory/?domain=1whois.ru

**Comment by msva** [comment]
Поменять подсеть для организации намного тяжелее, чем пользователю "домашнего 
интернета" получить новый IP-адрес из подсети этого же провайдера (а старый 
адрес провайдер выдаст другому пользователю). Я даже сам так несколько раз 
сталкивался с банами и блеклистами ни за что (из-за того, что предыдущий 
владелец IP был спамером и редиской).

**Comment by ache** [comment]
Там не совсем домашний юзер, там, похоже, дедикатед с пачкой виртуал хостов, принадлежащих тому же человеку (о нём в заметке на LJ). Как юрлицо этот провайдер сейчас поглощен Ростелекомом, и вместо провайдера там хостинг hc.ru
Ну не знаю, вам решать.

**Comment by msva** [comment]
Ну, я точно видел живых "простых смертных" в IRC с этого провайдера. Правда, 
не скажу как давно это было последний раз.
Но, впринципе, можно и добавить

// а давайте голосование устроим. У гитхаба, вон, реакции для этого появились 
как раз.
Пусть другие участники проекта заходят и ставят +1 или -1. А через пару дней 
(как руки дойдут) я добавлю :)

// впрочем, был бы Pull Request — было бы легче :)

**Comment by ache** [comment]
Вот ещё момент, просканил всю эту подсетку. Несмотря на то, что бак-адреса резолвятся как для юзеров провайдера, там везде сплошь сервера (Apache, nginx, IIS и пр. различные ftpd) - такое нереально на сетке для домашних юзеров.

**Comment by ache** [comment]
До кучи, инфа по НКС, что делала, когда была поглощена:
https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%BA%D0%B0%D0%B1%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D1%81%D0%B5%D1%82%D0%B8

**Comment by ache** [comment]
Пара дней прошли, разумеется, никто не проголосовал, потому что кроме нас всем пофиг, пока с ними не случится. Вместо хоть каких-нибудь действий люди предпочитают в дискуссиях поюморить на тему РКН. Извините за оффтоп.

**Comment by msva** [comment]
Closed with ea0a4ee

**Comment by ache** [comment]
Благодарю! А старый-то зачем от 2012 года 217.172.31.171? Он уж переехал на текущий хостинг. В 2014 (как раз год записи в ЖЖ) пытался метаться на 109.70.26.37, но вернулся обратно на 77.37.208.110. Тогда уж 109.70.26.37 было бы логичнее, нет?

**Comment by ache** [comment]
А нет, всё правильно 109.70.26.37 это expirepages-kiae-1.nic.ru, забыл оплатить домен.

**Comment by msva** [comment]
А старый - потому что он до сих пор указан в MX-записи. Значит у админа до него до сих пор есть доступ :) Значит может и с него :)

А вообще, я уже подумал, что надо разделить блеклист на разные списки:
- госорганы
- копирасты
- прочие педерасты (Л~~Г~~БИ и прочие 1whois)

**Comment by ache** [comment]
Науку, СМИ ещё можно отдельно.
Вот ещё по мелочи:
1) у "Пермский Роспотребнадзор" слишком дофига почти одинаковых сеток, лучше сократить уменьшением маски.
2) См. #56 
3) Вот здесь лучше написать, что Волгоград для ясности, а то выглядит как главный:
\# name: Роспотребнадзор
213.234.11.4/30
...

**Comment by ache** [comment]
4) ФСКН упразднена, см. fskn.gov.ru. Спецсвязи там тоже нет. Так что можно выкинуть
\# name: ФСКН, fskn.gov.ru
82.112.188.0/24
В этом же блоке Спецсвязь, но она осталась на старой подсети
\# netname: SPEZSVYAZ
\# descr: SPEZSVYAZ Internal network
\# Старая подсеть: 78.108.192.0/20
Так что или откомментить или выкинуть.

**Comment by ache** [comment]
Аналогично все региональные ФСКН наверно надо выкинуть.
