### ISSUE TITLE
РКН

### ISSUE THREAD

**Issue by cybergrom** [AntiZapret/antizapret#65]
https://apps.db.ripe.net/db-web-ui/#/lookup?source=ripe&key=87.226.213.0%20-%2087.226.213.255&type=inetnum
inetnum:         87.226.213.0 - 87.226.213.255
netname:         Roskomnadzor-net
country:         RU
descr:           Client of JSC Rostelecom
admin-c:         RTNC-RIPE
tech-c:          RTNC-RIPE
status:          ASSIGNED PA
mnt-by:          ROSTELECOM-MNT
created:         2017-01-24T08:19:21Z
last-modified:   2017-01-24T08:19:21Z
source:          RIPE

**Comment by msva** [comment]
Можно было и пулл-реквестом :)
Сейчас добавлю :)
